services:
  asr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asr-service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
